### ISSUE TITLE
Fix: Responsive(thumbnail)

### ISSUE THREAD

**Issue by deepakgithub11** [lubusIN/wpui#78]
Fix Thumbnail(Cards) responsive for safari/chrome
![IMG_8553](https://github.com/user-attachments/assets/218495fd-8596-4198-9ccb-a233e5112396)
![IMG_8552](https://github.com/user-attachments/assets/c5f7ccca-d925-46b1-9a0e-1cb92d2f855b)

**Comment by ajitbohra** [comment]
closing this unable to re-produce on master
